name: Test scripts and Docker image build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set TERM environment variable
        run: echo "TERM=xterm" >> $GITHUB_ENV

      - name: Test submodule patches script
        run: ./scripts/setup-submodule-patches.sh

      - name: Test environment setup script
        run: ./scripts/setup-environment.sh 1.1.1.1 2.2.2.2

      - name: Upload environment files
        uses: actions/upload-artifact@v4
        with:
          name: environment
          path: ./environment/

      - name: Validate Docker Compose file
        run: docker compose config

      - name: Build Docker images
        uses: docker/bake-action@v4
        with:
          pull: true
          load: true
          push: false
          set: |
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max
