name: Test scripts and build Docker images

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set TERM environment variable
        run: echo "TERM=xterm" >> "$GITHUB_ENV"

      - name: Apply Docker Compose CI overrides
        run: ln -s compose.override.yml .github/compose.ci.yml

      - name: Run the setup script
        run: ./setup.sh --server-ip 127.0.0.1 --force

      - name: Test starting the servers
        run: |
          docker compose up -d
          echo Waiting for 60 seconds...
          sleep 60
          docker compose ps -a
          docker compose logs
          # Fail if any containers exited
          ! docker compose ps -a | grep Exited
