name: Test scripts and build Docker images

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set TERM environment variable
        run: echo "TERM=xterm" >> $GITHUB_ENV

      - name: Run the setup script
        run: ./setup.sh

      - name: Build Docker images
        uses: docker/bake-action@v4
        with:
          pull: true
          load: true
          push: false
          set: |
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max
